Update project repository

diff --git a/usr/share/snoopgod/usr/bin/ucleaner b/usr/share/snoopgod/usr/bin/ucleaner
--- a/usr/share/snoopgod/usr/bin/ucleaner
+++ b/usr/share/snoopgod/usr/bin/ucleaner
@@ -34,7 +34,7 @@ function showwarning()
     echo -e "${texterror}You are about to clean all user temporary cached files and folders${textreset}"
     echo -e "${texterror}We recommend to exit all other programs before to proceed${textreset}"
     echo
-    read -p "Do you want to continue? [y/N] " yn
+    read -p "[?] Do you want to continue? [y/N] " yn
     case $yn in
         [Yy]* )
 			echo
@@ -46,6 +46,17 @@ function showwarning()
             exit
             ;;
     esac
+}
+
+## Check for root user
+## -------------------
+checkroot()
+{
+	if [[ ! $EUID -ne 0 ]];
+	then
+		echo "[!] Script cannot run as root" 1>&2
+	   	exit 1
+	fi
 }
 
 ## Secure delete
@@ -356,7 +367,7 @@ function deletetrash()
 ## ---------
 function terminate()
 {
-	echo "Process completed"
+	echo "[+] Process completed"
 	sleep 1s
 }
 
@@ -374,6 +385,7 @@ function launch()
 	# Prepare Environment
 	clearscreen
 	showwarning
+	checkroot
 	
 	# Execute Actions
 	deletecachechrome
@@ -397,7 +409,7 @@ function launch()
 	# Return notice
 	endtime=`date +%s.%N`
 	runtime=$( echo "$endtime - $flushtime" | bc -l )
-	echo "Executed within ${runtime} seconds"
+	echo "[+] Executed within ${runtime} seconds"
 }
 
 ## -------- ##
